version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  postgres:
    image: postgres:13
    container_name: postgres13
    environment:
      POSTGRES_USER: secret.POSTGRES_USER
      POSTGRES_PASSWORD: secret.POSTGRES_PASS
      POSTGRES_DB: secret.POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

