services:
  app:
    build:
      context: .

  postgres:
    image: "postgres:13"
    container_name: postgres13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qawsed
      POSTGRES_DB: dnd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

