all_spells = {
    'Identify': ['1st', '1 minute', 'Instantaneous', 'Divination', 'Touch', 'None', 'V, S',
                 'You choose one object that you must touch throughout the casting of the spell. If it is a magic item or some other magic-imbued object, you learn its properties and how to use them, whether it requires attunement to use, and how many charges it has, if any.'],
    'Poison Spray': ['Cantrip', '1 Action', 'Instantaneous', 'Conjuration', '10 feet', 'Constitution', 'V, S',
                     'You extend your hand toward a creature you can see within range and project a puff of noxious gas from your palm. The creature must succeed on a Constitution saving throw or take 1d12 poison damage.'],
    'Fog Cloud': ['1st', '1 Action', 'Up to 1 hour', 'Conjuration', '120 feet', 'None', 'V, S',
                  'You create a 20-foot-radius sphere of fog centered on a point within range. The sphere spreads around corners, and its area is heavily obscured.'],
    'Spare the Dying': ['Cantrip', '1 Action', 'Instantaneous', 'Necromancy', 'Touch', 'None', 'V',
                        'You touch a living creature that has 0 hit points. The creature becomes stable.'],
    'Entangle': ['1st', '1 Action', 'Up to 1 minute', 'Conjuration', '90 feet', 'Strength', 'V, S',
                 'Grasping weeds and vines sprout from the ground in a 20-foot square starting from a point within range. For the duration, these plants turn the ground in the area into difficult terrain.'],
    'Guiding Bolt': ['1st', '1 Action', 'Instantaneous', 'Evocation', '120 feet', 'None', 'V, S',
                     'A flash of light streaks toward a creature of your choice within range. Make a ranged spell attack against the target.'],
    'Burning Hands': ['1st', '1 Action', 'Instantaneous', 'Evocation', 'Self (15-foot cone)', 'Dexterity', 'V, S',
                      'As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth from your outstretched fingertips.'],
    'Sleep': ['1st', '1 Action', '1 minute', 'Enchantment', '90 feet', 'None', 'V, S, M',
              'This spell sends creatures into a magical slumber. Roll 5d8; the total is how many hit points of creatures this spell can affect.'],
    'Thaumaturgy': ['Cantrip', '1 Action', '1 minute', 'Transmutation', '30 feet', 'None', 'V',
                    'You manifest a minor wonder, a sign of supernatural power, within range.'],
    'Magic Missile': ['1st', '1 Action', 'Instantaneous', 'Evocation', '120 feet', 'None', 'V, S',
                      'You create three glowing darts of magical force.'],
    'Feather Fall': ['1st', '1 Reaction', '1 minute', 'Transmutation', '60 feet', 'None', 'V, M',
                     'Choose up to five falling creatures within range. A falling creature`s rate of descent slows to 60 feet per round until the spell ends.'],
    'Thunderwave': ['1st', '1 Action', 'Instantaneous', 'Evocation', 'Self (15-foot cube)', 'Constitution', 'V, S',
                    'A wave of thunderous force sweeps out from you.'],
    'Protection from Evil and Good': ['1st', '1 Action', 'Concentration, up to 10 minutes', 'Abjuration', 'Touch',
                                      'None', 'V, S, M',
                                      'Until the spell ends, one willing creature you touch is protected against certain types of creatures.'],
    'Disguise Self': ['1st', '1 Action', '1 hour', 'Illusion', 'Self', 'None', 'V, S',
                      'You make yourself—including your clothing, armor, weapons, and other belongings on your person—look different until the spell ends or until you use your action to dismiss it.'],
    'Illusory Script': ['1st', '1 Minute', '10 days', 'Illusion', 'Touch', 'None', 'S, M',
                        'You write on parchment, paper, or some other suitable writing material and imbue it with a potent illusion that lasts for the duration.'],
    'Cure Wounds': ['1st', '1 Action', 'Instantaneous', 'Evocation', 'Touch', 'None', 'V, S',
                    'A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier.'],
    'Guidance': ['Cantrip', '1 Action', '1 minute', 'Divination', 'Touch', 'None', 'V, S',
                 'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice.'],
    'Animal Friendship': ['1st', '1 Action', '24 hours', 'Enchantment', '30 feet', 'None', 'V, S, M',
                          'This spell lets you convince a beast that you mean it no harm.'],
    'Detect Magic': ['1st', '1 Action', 'Up to 10 minutes', 'Divination', 'Self', 'None', 'V, S',
                     'For the duration, you sense the presence of magic within 30 feet of you.'],
    'Druidcraft': ['Cantrip', '1 Action', 'Instantaneous', 'Transmutation', '30 feet', 'None', 'V, S',
                   'Whispering to the spirits of nature, you create one of the following effects within range.'],
    'Sacred Flame': ['Cantrip', '1 Action', 'Instantaneous', 'Evocation', '60 feet', 'Dexterity', 'V, S',
                     'Flame-like radiance descends on a creature that you can see within range.'],
    'Shield': ['1st', '1 Reaction', '1 round', 'Abjuration', 'Self', 'None', 'V, S',
               'An invisible barrier of magical force appears and protects you.'],
    'Hunter’s Mark': ['1st', '1 Bonus Action', '1 hour', 'Divination', '90 feet', 'None', 'V',
                      'You choose a creature you can see within range and mystically mark it as your quarry.'],
    'Grease': ['1st', '1 Action', '1 minute', 'Conjuration', '60 feet', 'Dexterity', 'V, S, M',
               'Slick grease covers the ground in a 10-foot square centered on a point within range.'],
    'Produce Flame': ['Cantrip', '1 Action', '10 minutes', 'Conjuration', 'Self', 'Attack', 'V, S',
                      'A flickering flame appears in your hand.'],
    'Vicious Mockery': ['Cantrip', '1 Action', 'Instantaneous', 'Enchantment', '60 feet', 'Wisdom', 'V',
                        'You unleash a string of insults laced with subtle enchantments at a creature you can see within range.'],
    'Ray of Sickness': ['1st', '1 Action', 'Instantaneous', 'Necromancy', '60 feet', 'Constitution', 'V, S',
                        'A ray of sickening greenish energy lashes out toward a creature within range.'],
    'Hellish Rebuke': ['1st', '1 Reaction', 'Instantaneous', 'Evocation', '60 feet', 'Dexterity', 'V, S',
                       'You point your finger, and the creature that damaged you is momentarily surrounded by hellish flames.'],
    'Heroism': ['1st', '1 Action', '1 minute', 'Enchantment', 'Touch', 'None', 'V, S',
                'A willing creature you touch is imbued with bravery.'],
    'Message': ['Cantrip', '1 Action', '1 round', 'Transmutation', '120 feet', 'None', 'V, S, M',
                'You point your finger toward a creature within range and whisper a message.'],
    'Healing Word': ['1st', '1 Bonus Action', 'Instantaneous', 'Evocation', '60 feet', 'None', 'V',
                     'A creature of your choice that you can see within range regains hit points equal to 1d4 + your spellcasting ability modifier.'],
    'Create or Destroy Water': ['1st', '1 Action', 'Instantaneous', 'Transmutation', '30 feet', 'None', 'V, S, M',
                                'You either create or destroy water.'],
    'Sanctuary': ['1st', '1 Bonus Action', '1 minute', 'Abjuration', '30 feet', 'None', 'V, S, M',
                  'You ward a creature within range against attack.'],
    'Silent Image': ['1st', '1 Action', '10 minutes', 'Illusion', '60 feet', 'None', 'V, S, M',
                     'You create the image of an object, a creature, or some other visible phenomenon that is no larger than a 15-foot cube.'],
    'Unseen Servant': ['1st', '1 Action', '1 hour', 'Conjuration', '60 feet', 'None', 'V, S, M',
                       'This spell creates an invisible, mindless, shapeless force that performs simple tasks.'],
    'Chill Touch': ['Cantrip', '1 Action', '1 round', 'Necromancy', '120 feet', 'Attack', 'V, S',
                    'You create a ghostly, skeletal hand in the space of a creature within range.'],
    'True Strike': ['Cantrip', '1 Action', '1 round', 'Divination', '30 feet', 'None', 'S',
                    "You extend your hand and point a finger at a target in range. Your magic grants you a brief insight into the target's defenses."],
    'Bane': ['1st', '1 Action', 'Concentration, up to 1 minute', 'Enchantment', '30 feet', 'Charisma', 'V, S, M',
             'Up to three creatures of your choice that you can see within range must make Charisma saving throws.'],
    'Resistance': ['Cantrip', '1 Action', '1 round', 'Abjuration', 'Touch', 'None', 'V, S, M',
                   'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one saving throw of its choice.'],
    'Light': ['Cantrip', '1 Action', '1 hour', 'Evocation', 'Touch', 'None', 'V, M',
              'You touch one object that is no larger than 10 feet in any dimension.'],
    'Eldritch Blast': ['Cantrip', '1 Action', 'Instantaneous', 'Evocation', '120 feet', 'Attack', 'V, S',
                       'A beam of crackling energy streaks toward a creature within range.'],
    'Find Familiar': ['1st', '1 hour', 'Instantaneous', 'Conjuration', '10 feet', 'None', 'V, S, M',
                      'You gain the service of a familiar, a spirit that takes an animal form you choose.'],
    'Speak with Animals': ['1st', '1 Action', '10 minutes', 'Divination', 'Self', 'None', 'V, S',
                           'You gain the ability to comprehend and verbally communicate with beasts for the duration.'],
    'Animal': ['1st', '1 Action', 'Instantaneous', 'Enchantment', '30 feet', 'Wisdom', 'V, S',
               'You attempt to charm a beast you can see within range.'],
    'Longstrider': ['1st', '1 Action', '1 hour', 'Transmutation', 'Touch', 'None', 'V, S, M',
                    'You touch a creature. The target`s speed increases by 10 feet until the spell ends.'],
    'Shillelagh': ['Cantrip', '1 Bonus Action', '1 minute', 'Transmutation', 'Touch', 'Attack', 'V, S, M',
                   'The wood of a club or quarterstaff you are holding is imbued with nature’s power.'],
    'Charm Person': ['1st', '1 Action', '1 hour', 'Enchantment', '30 feet', 'Wisdom', 'V, S',
                     'You attempt to charm a humanoid you can see within range.'],
    'Alarm': ['1st', '1 Minute', '8 hours', 'Abjuration', '30 feet', 'None', 'V, S, M',
              'You set an alarm against unwanted intrusion.'],
    'Mage Armor': ['1st', '1 Action', '8 hours', 'Abjuration', 'Touch', 'None', 'V, S, M',
                   'You touch a willing creature who isn’t wearing armor, and a protective magical force surrounds it until the spell ends.'],
    'Goodberry': ['1st', '1 Action', 'Instantaneous', 'Transmutation', 'Touch', 'None', 'V, S, M',
                  'Up to ten berries appear in your hand and are infused with magic for the duration.'],
    'Dancing Lights': ['Cantrip', '1 Action', '1 minute', 'Evocation', '120 feet', 'None', 'V, S',
                       'You create up to four torch-sized lights within range, making them appear as torches, lanterns, or glowing orbs.'],
    'Detect Evil and Good': ['1st', '1 Action', 'Concentration, up to 10 minutes', 'Divination', 'Self', 'None', 'V, S',
                             'For the duration, you know if there is an aberration, celestial, elemental, fey, fiend, or undead within 30 feet of you.'],
    'Command': ['1st', '1 Action', '1 round', 'Enchantment', '60 feet', 'Wisdom', 'V',
                'You speak a one-word command to a creature you can see within range.'],
    'Acid Splash': ['Cantrip', '1 Action', 'Instantaneous', 'Conjuration', '60 feet', 'Dexterity', 'V, S',
                    'You hurl a bubble of acid.'],
    'Mage Hand': ['Cantrip', '1 Action', '1 minute', 'Conjuration', '30 feet', 'None', 'V, S',
                  'A spectral, floating hand appears at a point you choose within range.'],
    'Shield of Faith': ['1st', '1 Bonus Action', 'Concentration, up to 10 minutes', 'Abjuration', '60 feet', 'None',
                        'V, S, M', 'A shimmering field appears and surrounds a creature of your choice within range.'],
    'Jump': ['1st', '1 Action', '1 minute', 'Transmutation', 'Touch', 'None', 'V, S, M',
             'You touch a creature. The creature’s jump distance is tripled until the spell ends.'],
    'Expeditious Retreat': ['1st', '1 Bonus Action', 'Concentration, up to 10 minutes', 'Transmutation', 'Self', 'None',
                            'V, S', 'This spell allows you to move at an incredible pace.'],
    'Minor Illusion': ['Cantrip', '1 Action', '1 minute', 'Illusion', '30 feet', 'None', 'S, M',
                       'You create a sound or an image of an object within range that lasts for the duration.'],
    'Divine Favor': ['1st', '1 Bonus Action', '1 minute', 'Evocation', 'Self', 'None', 'V, S',
                     'Your prayer empowers you with divine radiance.'],
    'Friendship': ['1st', '1 Action', '1 hour', 'Enchantment', '30 feet', 'Wisdom', 'S, M',
                   'For the duration, you have advantage on all Charisma checks directed at one creature of your choice that isn’t hostile toward you.'],
    'Mending': ['Cantrip', '1 Minute', 'Instantaneous', 'Transmutation', 'Touch', 'None', 'V, S, M',
                'This spell repairs a single break or tear in an object you touch.'],
    'Purify Food and Drink': ['1st', '1 Action', 'Instantaneous', 'Transmutation', '10 feet', 'None', 'V, S',
                              'All nonmagical food and drink within a 5-foot-radius sphere centered on a point of your choice within range is purified and rendered free of poison and disease.'],
    'False Life': ['1st', '1 Action', '1 hour', 'Necromancy', 'Self', 'None', 'V, S, M',
                   'Bolstering yourself with a necromantic facsimile of life, you gain 1d4 + 4 temporary hit points for the duration.'],
    'Prestidigitation': ['Cantrip', '1 Action', 'Up to 1 hour', 'Transmutation', '10 feet', 'None', 'V, S',
                         'This spell is a minor magical trick that novice spellcasters use for practice.'],
    'Ray of Frost': ['Cantrip', '1 Action', 'Instantaneous', 'Evocation', '60 feet', 'Attack', 'V, S',
                     'A frigid beam of blue-white light streaks toward a creature within range.'],
    'Detect Poison and Disease': ['1st', '1 Action', 'Instantaneous', 'Divination', '30 feet', 'None', 'V, S',
                                  'For the duration, you can sense the presence and location of poisons, poisonous creatures, and diseases within 30 feet of you.'],
    'Faerie Fire': ['1st', '1 Action', 'Concentration, up to 1 minute', 'Evocation', '60 feet', 'Dexterity', 'V',
                    'Each object in a 20-foot cube within range is outlined in blue, green, or violet light.'],
    'Inflict Wounds': ['1st', '1 Action', 'Instantaneous', 'Necromancy', 'Touch', 'Attack', 'V, S',
                       'Make a melee spell attack against a creature you can reach.'],
    'Shocking Grasp': ['Cantrip', '1 Action', 'Instantaneous', 'Evocation', 'Touch', 'Attack', 'V, S',
                       'Lightning springs from your hand to deliver a shock to a creature you try to touch.'],
    'Color Spray': ['1st', '1 Action', 'Instantaneous', 'Illusion', 'Self (15-foot cone)', 'None', 'V, S, M',
                    'A dazzling array of flashing, colored light springs from your hand.'],
    'Fire Bolt': ['Cantrip', '1 Action', 'Instantaneous', 'Evocation', '120 feet', 'Attack', 'V, S',
                  'You hurl a mote of fire at a creature or object within range.'],
    'Bless': ['1st', '1 Action', 'Concentration, up to 1 minute', 'Enchantment', '30 feet', 'None', 'V, S, M',
              'You bless up to three creatures'],
    'Comprehend Languages': ['1', '1 action', '1 hour', 'Divination', 'Self', 'None', 'V, S, M',
                             'For the duration, you understand the literal meaning of any spoken language that you hear.']
}
